GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5f7c61db0c45f5203ae6900d

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "amazing person",
"subscribedToChannel": "web dev simplified"
}

###

DELETE http://localhost:3000/subscribers/5f7c61db0c45f5203ae6900d